#!/usr/bin/env python

import logging

from argqueue.parser import get_arguments
from argqueue.queue import Queue

def done(queue, args):
  queue.status(args.args_id, update='DONE')

def exit_command(queue, args):
  queue.status(args.args_id, update='EXIT')

def get(queue, args):
  print queue.get(args.args_id)

def lease(queue, args):
  print queue.lease(timeout=args.timeout)

def put(queue, args):
  for arguments in args.arguments:
    logging.debug("Adding the following arguments: '%s'" % arguments)
    queue.put(arguments)

def pop(queue, args):
  logging.debug("Popping some arguments")
  print queue.pop()

if __name__ == '__main__':
  logging.basicConfig(level=logging.WARN)
  args = get_arguments()
  queue = Queue(args.database.name)
  func_lookup = {
    'done': done,
    'exit': exit_command,
    'get': get,
    'lease': lease,
    'pop': pop,
    'put': put
  }
  func = func_lookup[args.sub_command]
  func(queue, args)
