#!/usr/bin/env python

import logging

from jobqueue.parser import get_arguments
from jobqueue.queue import Queue

def done(queue, args):
  queue.status(args.job_id, update='DONE')

def exit_command(queue, args):
  queue.status(args.job_id, update='EXIT')

def get(queue, args):
  print queue.get(args.job_id)

def lease(queue, args):
  print queue.lease(timeout=args.timeout)

def put(queue, args):
  for job in args.jobs:
    logging.debug("Adding the following job: '%s'" % job)
    queue.put(job)

def pop(queue, args):
  logging.debug("Popping a job")
  print queue.pop()

if __name__ == '__main__':
  logging.basicConfig(level=logging.WARN)
  args = get_arguments()
  queue = Queue(args.database.name)
  func_lookup = {
    'done': done,
    'exit': exit_command,
    'get': get,
    'lease': lease,
    'pop': pop,
    'put': put
  }
  func = func_lookup[args.sub_command]
  func(queue, args)
